When ++/-- used in thread, reply with points in that thread
Conway/pluspl.us pull request #72
Opened 2020-05-21 17:23 UTC by LukeHowellDev

When pluspl.us is used in threaded messages, the points will be shown in that thread.

I am new to Slack development and I'm not certain how to test this update. If I can get some guidance on testing, I will be happy to test it out.

2020-05-21 20:04 UTC, Conway requested changes
Thanks for making this pull request! Just a few minor changes are needed to make this valid Python so I can test it.

2020-05-21 20:04 UTC, Conway commented on plusplus/operations/slack_handler.py
> +    thread_ts = subtype === 'message_replied' ? event.get('event_ts') : ''
I don't think this is valid in Python (ternaries in Python are done like `variable = value_if_true if condition else value_if_false`)

2020-05-21 20:04 UTC, Conway commented on plusplus/operations/slack_handler.py
> +        post_message(message, channel, thread_ts)
Thanks for refactoring this into a method :)

2020-05-21 20:04 UTC, Conway commented on plusplus/operations/slack_handler.py
> +def post_message(message, channel, thread_ts = ''):
Nit: Please change the last argument to `thread_ts=''` to match the code style

2020-05-21 20:04 UTC, Conway commented on plusplus/operations/slack_handler.py
> +    if parent_ts === '':
This should be a double equals not a triple equals

2020-05-21 20:17 UTC, LukeHowellDev commented
@Conway Thanks for the feedback on this. I have pushed the requested changes.

2020-05-26 21:01 UTC, Conway commented
Thanks for making those changes @LukeHowellDev! I will test the changes this week

2020-06-01 05:08 UTC, merged